version: "3"

services:

  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/usr/src/app/:rw
    environment:
      - NODE_ENV=dev

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./public:/wwwroot
      - ./server/log:/var/log/nginx




