version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./public:/wwwroot
      #- ./server/log:/var/log/nginx

  webpack:
    build:
      context: ./config
      dockerfile: Dockerfile
    volumes:
      - ../:/app
